# Generated by Django 5.1.2 on 2024-10-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_city_comment_city_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='city_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
